[theme]
base            = "dark"
primaryColor    = "#C9A96E"
backgroundColor = "#0D0D0D"
secondaryBackgroundColor = "#141414"
textColor       = "#EEEEF5"
font            = "sans serif"

[server]
maxUploadSize   = 10
enableXsrfProtection = true
